const { json } = require("express");

console.log("Hello world");

// Variable in javacript

// let const var

let Today = "Monday";
Today = "Yesterday";
console.log(Today);

const Day = "Afternoon";
console.log(Day);

var Language = "Javascript";
Language = "Python";
console.log(Language);

var Language = "JavaScript";

{
  let Gender = "Female";
}
console.log(Gender);
let Gender = "Male";

// DataTypes in Javascript
// strings
// number
// Boolean
// object
// Array
// undefined
// Null

let Name = "Tomaket";
let Age = 18;
let sentence = `i am ${Name} and i am ${Age} years old`;
console.log(sentence);

let hungry = true;
console.log(typeof hungry);

let Person = {
  Name: "Tomaket",
  Age: 18,
  Location: "Central Area",
  MusicTastes: "Amapiano",
  Picture: "./",
  isMale: false,
};
console.log(Person.Name);

let Fruits = ["Apple", "Orange", "Banana", "Garden Egg"];
// console.log(Fruits[0]);
// console.log(Fruits.length);
console.log(Fruits.length - 1);

let x = undefined;
console.log(x);

let empty = "";
console.log(typeof empty);

// Types of Datatypes in js
// primitive datatypes
// 1. Numbers - Integers, floats
//  2. Strings - Any data under single quote, double quote or backtick quote
//  3. Booleans - true or false value
//  4. Null - empty value or no value
//  5. Undefined - a declared variable without a value
//  6. Symbol - A unique value that can be generated by Symbol constructor

// AND the Non primitive datatTypes
// 1. Objects
// 2. Arrays

// Math operators in js
let Pi = Math.PI 
console.log(Pi);
console.log(Math.round(Pi));
console.log(Math.floor(Pi))   

let books = 10.55
console.log(Math.floor(books));

console.log(Math.ceil(Pi)) 

console.log(Math.min(-5, 3, 2, -200));
console.log(Math.max(-5, 3, 2, -200));

const ranNumber = Math.random()
console.log(ranNumber);


const num = Math.floor(Math.random () * 11) // creates random number between 0 and 10
console.log(num)

console.log(Math.abs(-10)) 

console.log(Math.sqrt(100)) 
console.log(Math.pow(3, 2))


console.log(Math.E)          

console.log(Math.log(2)) 
console.log(Math.LN10)

// string concatenation 
let space = ' '           // an empty space string
let firstName = 'Asabeneh'
let lastName = 'Yetayeh'
let country = 'Finland'
let city = 'Helsinki'
let language = 'JavaScript'
let job = 'teacher'
let quote = "The saying,'Seeing is Believing' is not correct in 2020."
let quotWithBackTick = `The saying,'Seeing is Believing' is not correct in 2020.`

let fullName = firstName + space + lastName 
console.log(fullName);


let data1 = '4'
let data2 = 4
let result = data1 + data2
console.log(result);


// Escape Sequences in Strings
console.log('I hope everyone is enjoying the 30 Days Of JavaScript challenge.\nDo you ?') // line break
console.log('Days\tTopics\tExercises')
console.log('Day 1\t3\t5')
console.log('Day 2\t3\t5')
console.log('Day 3\t3\t5')
console.log('Day 4\t3\t5')
console.log('This is a backslash  symbol (\\)') // To write a backslash
console.log("In every programming language it starts with \'Hello, World!' " )
console.log("In every programming language it starts with \'Hello, World!\'")
console.log('The saying \'Seeing is Believing\' isn\'t correct in 2020')

// Strings Method in js 
let Country = 'Nigeria'
let words = Country.toUpperCase()
let another =words.concat(' is a country')
console.log(another);


// conditional statements in javascript 
let leaving = false;
let currentTime = 258
let choiceOfLeaving = true
let time = 300

// if(currentTime >= time ){
//     console.log('she is leaving the class');   
// }else {
//     console.log('she is not leaving the class');
// }

if(currentTime >= time){
    console.log('she is leaving the class');
}else if(choiceOfLeaving){
    console.log('I am tired i want Go');
}else{
    console.log('she is not leaving the class');
}

